### ISSUE TITLE
Name template

### ISSUE THREAD

**Issue by tguichaoua** [zwpaper/obsidian-progressbar#4]
Allow the `name` parameter to accept template for better customization.

Possible value that can be inserted in the name :
- `$value` : render into the value
- `$max` : render into the maximum value
- `$percentage`: render into `value/max * 100` rounded

Note: I use `$` as prefix, but it will probably depend on the template engine used.

Examples :

```yml
- name: My super progress bar [$value / $max]
- value: 10
- max: 100
```
```
My super progress bar [10 / 100]
```
```yml
- name: My tasks ($percentage %)
- value: 10
- max: 50
```
```
My tasks (20 %)
```
